name: Node.js CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Debug Cache
      run: "echo \"Cache Key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}\""

    - name: Cache Node.js modules
      uses: actions/cache@v3
      with:
        path: node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
          ${{ runner.os }}-

    - name: Install dependencies
      run: npm ci --silent

    - name: Verify Cache Restoration
      run: ls -la node_modules

    - name: Run tests
      env:
        CI: true
        NODE_OPTIONS: --experimental-vm-modules
      run: npm run test:ci
